# Site settings
title: IoT Kit Hands-on Training Site
email: iotkithol-jp@microsoft.com
description: ""
baseurl: ""
url: "http://aka.ms/IoTKitHoL"

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink: pretty
highlighter: pygments
